[package]
name = "way-title-printer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wayland-client = "0.31.2"
wayland-protocols-wlr = { version = "0.2.0", features = ["wayland-client", "client"] }
